### ISSUE TITLE
InvalidOperationException when using inner records

### ISSUE THREAD

**Issue by dingbat1** [nenoNaninu/TypedSignalR.Client.TypeScript#120]
I am seeing an **InvalidOperationException** when trying to transpile the following record inside another record:

    [TranspilationSource]
    public record DestinationListDTO
        (IReadOnlyCollection<DestinationListDTO.Destination> Destinations)
    {
        [TranspilationSource]
        public record Destination(
               short? Address,
               string? Label1,
               string? Label2,
               short? Source)
        {
        }
    }

The error is below. I can resolve the error by moving the "Destination" definition outside of the "DestinationListDTO" record. So something not liking the record/custom type inside another record.

I've removed some of my namespace, but you get the idea.

`Transpile xxx.DestinationListDTO...
xxx.DestinationListDTO can not be transpiled.
======== Exception ========
System.InvalidOperationException: xxx.DestinationListDTO.Destination is not supported.
   at Tapper.DefaultTypeMapperProvider.GetTypeMapper(ITypeSymbol type)
   at Tapper.TypeMappers.IReadOnlyCollection1TypeMapper.MapTo(ITypeSymbol typeSymbol, ITranspilationOptions options)
   at Tapper.TypeMappers.TypeMapper.MapTo(ITypeSymbol typeSymbol, ITranspilationOptions options)
   at Tapper.TypeTranslators.DefaultMessageTypeTranslator.Translate(CodeWriter& codeWriter, INamedTypeSymbol typeSymbol, ITranspilationOptions options)
   at Tapper.TypeScriptCodeGenerator.AddType(INamedTypeSymbol typeSymbol, CodeWriter& writer)
   at Tapper.Transpiler.Transpile()
   at TypedSignalR.Client.TypeScript.App.TranspileCore(Compilation compilation, String outputDir, NewLineOption newLine, Int32 indent, Boolean referencedAssembliesTranspilation, SerializerOption serializerOption, NamingStyle namingStyle, EnumStyle enumStyle, MethodStyle methodStyle, Boolean enableAttributeReference) in /home/runner/work/TypedSignalR.Client.TypeScript/TypedSignalR.Client.TypeScript/src/TypedSignalR.Client.TypeScript.Generator/App.cs:line 133
   at TypedSignalR.Client.TypeScript.App.Transpile(String project, String output, NewLineOption newLine, Boolean assemblies, SerializerOption serializer, NamingStyle namingStyle, EnumStyle enum, MethodStyle method, Boolean attribute) in /home/runner/work/TypedSignalR.Client.TypeScript/TypedSignalR.Client.TypeScript/src/TypedSignalR.Client.TypeScript.Generator/App.cs:line 55`

**Comment by nenoNaninu** [comment]
Please create a repository to reproduce the problem and share its URL. In my environment, I was able to generate TypeScript code from the following code without any problems.

```cs
[Hub]
public interface IHub
{
    Task Set(DestinationListDTO obj);
    Task<DestinationListDTO> Get();
}

[TranspilationSource]
public record DestinationListDTO
    (IReadOnlyCollection<DestinationListDTO.Destination> Destinations)
{
    [TranspilationSource]
    public record Destination(
           short? Address,
           string? Label1,
           string? Label2,
           short? Source)
    {
    }
}
```

**Comment by dingbat1** [comment]
Thanks for testing and the quick response.
I might have a look at .NET version targets. My projects are NET6.0 but I am using SDK v7.0.306 as other projects are targeting 7.

**Comment by nenoNaninu** [comment]
The tests for this issue are working fine. If you're still having issues, please open an issue again with more details.
