### ISSUE TITLE
Support classes from different assembly in Typescript Client generation

### ISSUE THREAD

**Issue by Vulthil** [nenoNaninu/TypedSignalR.Client.TypeScript#27]
Would it be possible for the 'tsrts' tool to support generating Typescript clients when the User Defined types in the interfaces for the [Hub] and [Receiver], are defined in a different assembly ?

Currently the type

```
using Tapper;
namespace TestProject.Library;

[TranspilationSource]
public class TestClass
{
    public string Test { get; set; }
}
```

fails with:
```
System.InvalidOperationException: TestProject.Library.TestClass is not supported.
   at Tapper.DefaultTypeMapperProvider.GetTypeMapper(ITypeSymbol type)
   at Tapper.TypeMappers.TypeMapper.MapTo(ITypeSymbol typeSymbol, ITranspilationOptions options)
   at TypedSignalR.Client.TypeScript.InterfaceTranspiler.WriteParameters(IMethodSymbol methodSymbol, ITranspilationOptions options, CodeWriter& codeWriter) in /home/runner/work/TypedSignalR.Client.TypeScript/TypedSignalR.Client.TypeScript/src/TypedSignalR.Client.TypeScript/InterfaceTranspiler.cs:line 134
   at TypedSignalR.Client.TypeScript.InterfaceTranspiler.AddInterface(INamedTypeSymbol interfaceSymbol, SpecialSymbols specialSymbols, ITranspilationOptions options, CodeWriter& codeWriter) in /home/runner/work/TypedSignalR.Client.TypeScript/TypedSignalR.Client.TypeScript/src/TypedSignalR.Client.TypeScript/InterfaceTranspiler.cs:line 102
   at TypedSignalR.Client.TypeScript.InterfaceTranspiler.Transpile(IEnumerable`1 interfaceTypes) in /home/runner/work/TypedSignalR.Client.TypeScript/TypedSignalR.Client.TypeScript/src/TypedSignalR.Client.TypeScript/InterfaceTranspiler.cs:line 40
   at TypedSignalR.Client.TypeScript.TypedSignalRCodeGenerator.Generate() in /home/runner/work/TypedSignalR.Client.TypeScript/TypedSignalR.Client.TypeScript/src/TypedSignalR.Client.TypeScript/TypedSignalRCodeGenerator.cs:line 45
   at TypedSignalR.Client.TypeScript.App.TranspileCore(Compilation compilation, String outputDir, String newLine, Int32 indent, SerializerOption serializerOption, NamingStyle namingStyle, EnumNamingStyle enumNamingStyle) in /home/runner/work/TypedSignalR.Client.TypeScript/TypedSignalR.Client.TypeScript/src/TypedSignalR.Client.TypeScript.Generator/App.cs:line 107
   at TypedSignalR.Client.TypeScript.App.Transpile(String project, String output, String newLine, String serializer, String namingStyle, String enumNamingStyle) in /home/runner/work/TypedSignalR.Client.TypeScript/TypedSignalR.Client.TypeScript/src/TypedSignalR.Client.TypeScript.Generator/App.cs:line 67
```

when trying to transpile a Typescript client from the following interface:
```
using TypedSignalR.Client.TypeScript;
using TestProject.Library;
namespace TestProject.ClientInterface;

[Hub]
public interface ITest
{
    Task<TestClass> TestMethod(TestClass message);
}
```

This only seems to be an issues when the namespaces 'TestProject.Library' and 'TestProject.ClientInterface' are defined in different assemblies.

**Comment by nenoNaninu** [comment]
Different assembly means DLL? Currently, I do not anticipate that types in different DLLs will be the target for transpiling. PR is welcome.

**Comment by Vulthil** [comment]
Yes, a different assembly would mean a different DLL in this case.

Consider the case where a shared project is used storing DTOs for different transport protocols, e.g. SignalR or TCP or HTTP.
If the interfaces for the SignalR contracts resides in a different DLL than the DTOs, the transpiling will fail.

I looked at it a bit and the issue seems to be that
the function 
https://github.com/nenoNaninu/Tapper/blob/f36f7c811a916fb7cee7c51e24d49f0f27aa5080/src/Tapper/RoslynExtensions.cs#L11
```
public static IEnumerable<INamedTypeSymbol> GetNamedTypeSymbols(this Compilation compilation)
 ```
 
 Only includes types from the current .csproj file being processed.
 (This is in the Tapper repository)
 I fiddled with it, and was able to extract all types from the 
 ```
 compilation.GlobalNamespace
 ```
, which had the  `TranspilationSourceAttribute`.

However, I didn't do the filtering to only include the actual types being referenced from the current .csproj.
 I might continue digging, and providing a new Pull Request in the Tapper Repository.
 
 Maybe this issue could be moved there ?

**Comment by nenoNaninu** [comment]
Perhaps the following code may need to be modified at the same time as Tapper.

https://github.com/nenoNaninu/TypedSignalR.Client.TypeScript/blob/main/src/TypedSignalR.Client.TypeScript/RoslynExtensions.cs#L9-L23

**Comment by dingbat1** [comment]
I had some trouble with this initially, and was spinning my wheels for a bit.

Just wanted to note for anyone searching, that this issue is now solved. You need the "-asm" or "--assemblies" switch to reference other assemblies.

See the README for more details.

I have some SignalR hubs that inherit from bases in other assemblies, to get common functions and DTOs. This is working well once I found the right switches.
