### ISSUE TITLE
CancellationToken not supported

### ISSUE THREAD

**Issue by serard-bimandco** [nenoNaninu/TypedSignalR.Client.TypeScript#87]
Hello, 

First, thank you for this project.

I'm sure I'm not using it correctly.

Here are snippets of my code and usage and reported error :

IHub.cs
```
IAsyncEnumerable<StreamingLinesResponse> StreamEntitiesAsyncEnumerable(
        StreamingEntitiesRequest request,
        CancellationToken cancellationToken
    );

```

HubImpl.cs
```
[SignalRMethod]
    public async IAsyncEnumerable<StreamingLinesResponse> StreamEntitiesAsyncEnumerable(
        StreamingEntitiesRequest request,
        [EnumeratorCancellation] CancellationToken cancellationToken = default
    )
    {
        await foreach (StreamingLinesResponse i in _tableStreamer.StreamEntitiesAsync(request, cancellationToken)
                           .WithCancellation(cancellationToken))
            yield return i;
    }
```

Call
```
 dotnet tsrts --project .\My.Web.Api\My.Web.Api.csproj --output .\My.Web.Front\src\MySignalRClient
```

```
======== Exception ========
System.InvalidOperationException: System.Threading.CancellationToken is not supported.
   at Tapper.DefaultTypeMapperProvider.GetTypeMapper(ITypeSymbol type)
   at Tapper.TypeMappers.TypeMapper.MapTo(ITypeSymbol typeSymbol, ITranspilationOptions options)
   at TypedSignalR.Client.TypeScript.Templates.MethodSymbolExtensions.<>c__DisplayClass5_0.<ParametersToTypeArray>b__0(IParameterSymbol x) in /home/runner/work/TypedSignalR.Client.TypeScript/TypedSignalR.Client.TypeScript/src/TypedSignalR.Client.TypeScript/Templates/MethodSymbolExtensions.cs:line 83
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at TypedSignalR.Client.TypeScript.Templates.MethodSymbolExtensions.ParametersToTypeArray(IMethodSymbol methodSymbol, ITypedSignalRTranspilationOptions options) in /home/runner/work/TypedSignalR.Client.TypeScript/TypedSignalR.Client.TypeScript/src/TypedSignalR.Client.TypeScript/Templates/MethodSymbolExtensions.cs:line 84
   at TypedSignalR.Client.TypeScript.Templates.MethodSymbolExtensions.WrapLambdaExpressionSyntax(IMethodSymbol methodSymbol, ITypedSignalRTranspilationOptions options) in /home/runner/work/TypedSignalR.Client.TypeScript/TypedSignalR.Client.TypeScript/src/TypedSignalR.Client.TypeScript/Templates/MethodSymbolExtensions.cs:line 16
   at TypedSignalR.Client.TypeScript.Templates.ApiTemplate.TransformText() in /home/runner/work/TypedSignalR.Client.TypeScript/TypedSignalR.Client.TypeScript/src/TypedSignalR.Client.TypeScript/Templates/ApiTemplate.cs:line 141
   at TypedSignalR.Client.TypeScript.ApiGenerator.Generate(IReadOnlyList`1 hubTypes, IReadOnlyList`1 receiverTypes) in /home/runner/work/TypedSignalR.Client.TypeScript/TypedSignalR.Client.TypeScript/src/TypedSignalR.Client.TypeScript/ApiGenerator.cs:line 38
   at TypedSignalR.Client.TypeScript.TypedSignalRCodeGenerator.Generate() in /home/runner/work/TypedSignalR.Client.TypeScript/TypedSignalR.Client.TypeScript/src/TypedSignalR.Client.TypeScript/TypedSignalRCodeGenerator.cs:line 43
   at TypedSignalR.Client.TypeScript.App.TranspileCore(Compilation compilation, String outputDir, NewLineOption newLine, Int32 indent, Boolean referencedAssembliesTranspilation, SerializerOption serializerOption, NamingStyle namingStyle, EnumStyle enumStyle, MethodStyle methodStyle, Boolean enableAttributeReference) in /home/runner/work/TypedSignalR.Client.TypeScript/TypedSignalR.Client.TypeScript/src/TypedSignalR.Client.TypeScript.Generator/App.cs:line 125
   at TypedSignalR.Client.TypeScript.App.Transpile(String project, String output, NewLineOption newLine, Boolean assemblies, SerializerOption serializer, NamingStyle namingStyle, EnumStyle enum, MethodStyle method, Boolean attribute) in /home/runner/work/TypedSignalR.Client.TypeScript/TypedSignalR.Client.TypeScript/src/TypedSignalR.Client.TypeScript.Generator/App.cs:line 55
```

Thank you for your help !

Stéphane

**Comment by serard-bimandco** [comment]
Okay got it working.
